name: priorities
description: The simplest form of a todo list app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # For state management 
  stacked: ^3.0.0
  flutter_riverpod: ^2.1.1
  
  # Local storage
  hive: ^2.2.3

  # Service locator, to access the injected dependencies
  get_it: ^7.2.0

  # To access app documents directory
  path_provider: ^2.0.11

  # Emoji keyboard
  emoji_picker_flutter: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  
flutter:
  uses-material-design: true