name: priorities
description: The simplest form of a todo list app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # For state management 
  flutter_riverpod: ^2.1.1
  
  # For Data Classes
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  
  # Local storage
  hive: ^2.2.3

  # To access app documents directory
  path_provider: ^2.0.11

  # Emoji keyboard
  emoji_picker_flutter: ^1.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.3.2
  freezed: ^2.3.0
  json_serializable: ^6.5.4
  
flutter:
  uses-material-design: true