name: priorities
description: The simplest form of a todo list app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Will use Stacked for MVVM implementaion 
  stacked: ^2.3.6
  # Local storage
  hive: ^2.2.3
  # Will use get_it as a service locator, to access the injected dependencies
  get_it: ^7.2.0
  # To access app documents directory
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  
flutter:
  uses-material-design: true